baseURL = "https://canada-ca-youth-pod.netlify.com/"

languageCode = "en"

title = "Canada.ca Youth Pod Development Site"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "sitemap"]

theme = "cdts.canada.ca"

defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 10
  [languages.fr]
    contentDir = "content/fr"
    languageName = "Français"
    weight = 20